### ISSUE TITLE
Can't undo the liquidity BLZD-BNB

### ISSUE THREAD

**Issue by ramiroschiavoni** [blzd-dev/blzd-frontend#1]
Hello. I finalize a farm BLZD-BNB and I have my Cake-LP tokens in my wallet, but when I go to PancakeSwap to undo the liquidity it says I have none and I cannot import the pair of tokens because BLZD is not listed. It happen in TrustWallet and Metamask as well. What can I do to have my money back? Thank you so much!

**Comment by mrparadox9** [comment]
Steps for removing LP:
1. Make sure you've withdrawn your LP from any pool or vault

2. Under PCS Liquidity tab, wait for awhile to see if your LP is found. If not, click "Import It" and update the tokens. If you do not see BLZD in the list of tokens to select, you can manually add it by entering the BLZD address - 0x57067A6BD75c0E95a6A5f158455926e43E79BeB0

3. Once it says "Found", click the arrow to return to list of LP and you should be able to remove it now.

**Comment by ramiroschiavoni** [comment]
Yes, I totally did that! It was easy when I understand. Thank you much for your quick reply! Regards!
